### PR TITLE
Merge 6.1.0 release into master

### PR DESCRIPTION
**Pull request by arjantijms**
According to https://github.com/jakartaee/servlet/issues/651

### CODE REVIEW

**Comment by pzygielo** [comment]
Could the error https://github.com/jakartaee/servlet/actions/runs/9227838949/job/25390577146?pr=654#step:5:2728 be fixed within this PR to not pollute master with non-buildable state?

**Comment by markt-asf** [comment]
Not sure we really need to do this. I think renaming the 6.1.0 branch to 6.1.x and updating master to 6.2.0(-SNAPSHOT) would get us to where we need to be.

**Comment by arjantijms** [comment]
> Not sure we really need to do this. 

It's partially common practice, but also the exact commit that made 6.1.0 a fact would not be in the 6.2.0 branch then, right? Not sure if that's an issue by itself.

But most (all?) projects do it like this.

**Comment by markt-asf** [comment]
I guess I am -0 on this. I don;t really see the point but no objection. I'll rename the 6.1.0 branch to 6.0.x once you are done.

**Comment by arjantijms** [comment]
@markt-asf it is done

**Comment by markt-asf** [comment]
Tx. Branch renamed. I'll update the master branch to 6.2.x shortly.

**Pull request merged**
