### PR TITLE
fix the build as 6.1.0 is not available in Maven central

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by markt-asf** [comment]
Please revert. 6.1.0 is available from the staging repository.

**Comment by olamy** [comment]
Sure but please provide the url of staging repo to help people building the project (we should have it in the pom if it's mandatory to build the project)
Is this a final release or a staged release? I would like to avoid people downloading a non snapshot ja which could potentially change.

**Comment by markt-asf** [comment]
Good point. The TCK JAR could well change before the final release (hopefully not but you never know) and I agree downloading a non-snapshot JAR that is might change is not good. I suspect this will require a little more hoop jumping for the CI system so we don't end up with a released artifact that depends on a SNAPSHOT but let's see if we can address that in the CI system. I withdraw my request to revert this.

**Comment by arjantijms** [comment]
> Sure but please provide the url of staging repo to help people building the project (we should have it in the pom if it's mandatory to build the project) 

It is in the pom already, and you can activate it via the "-Pstaging" parameter.

See the parent pom;

```xml
    <parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.9</version>
        <relativePath/>
    </parent>
```

**Pull request merged**
