### PR TITLE
Import of the TCK code from platform branch tckrefactor hash f7ff710776d0a241fa50a25c97fad686283aa640

### PR DESCRIPTION
**Pull request by olamy**
- servlet tck code from git hash f7ff710776d0a241fa50a25c97fad686283aa640
- set some maven plugins versions

### CODE REVIEW

**Comment by markt-asf** [comment]
How much longer is this PR likely to be in draft? What is the (rough) plan to get this PR from where it is now to merged?

**Comment by olamy** [comment]
> How much longer is this PR likely to be in draft? What is the (rough) plan to get this PR from where it is now to merged?

Oh yes that's right. I will update the thread on servlet@ but it's ready.
This still need a lot of improvements though as it is old code but ready and works.

**Review by gregw — APPROVED** [review]
I've not really been able to review 1000+ files, but as this is primarily a move LGTM

**Review by markt-asf — APPROVED** [review]
I have tried to review the changes but there are too many unrelated formatting changes. I do have a concern that there may be some subtle changes.

I very much like the new style TCK and am keen to have this available for Servlet. I am happy to merge this on the basis if there are issues we may need to handle a few additional TCK challenges but that is a risk I can live with.

**Review by stuartwdouglas — APPROVED** [review]
I am also happy to go ahead with this. If there are any problems introduced we can address them as they discovered.

**Pull request merged**
